apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx
    envFrom:
    - configMapRef:
        name: my-config-map
    volumeMounts:
    - name: my-volume
      mountPath: "/etc/volume"
      readOnly: true
  volumes:
  - name: my-volume
    configMap:
      name: my-config-map

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
data:

  # connection database config
  config-db: | 
    database_name: mysql
    database_uri: mysql://localhost:3306
  
  # user interface config
  config-interface: |
    font.title: Arial Bold
    background-color: black