apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: Pod
metadata: 
  name: app-pod
  namespace: app
spec: 
  containers:
  - name: apache-container
    image: httpd
    resources:
      requests:
        cpu: "250m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"
  
  - name: redis-container
    image: redis
    resources:
      requests:
        cpu: "500m"
        memory: "256Mi"
      limits:
        cpu: "1000m"
        memory: "512Mi"