apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
  - name: redis-container
    image: redis
    volumeMounts:s
    - mountPath: "/external_data"
      name: "data"

  volumes:
  - name: "data"
    hostPath:
      path: "/var/lib/datapod"