apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: Pod
metadata: 
  name: web-pod
  namespace: app
  labels:
    type: web-app
spec: 
  containers:
    - name: web-server-apache
      image: httpd
      ports:
        - containerPort: 80
    - name: web-server-tomcat
      image: tomcat
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-loadbalancer
  namespace: app
spec:
  type: LoadBalancer
  selector:
    type: web-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30003