apiVersion: v1
kind: Pod
metadata:
  name: pod-apache
spec:
  containers:
  - name: container-apache
    image: httpd

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
spec:
  containers:
  - name: container-nginx
    image: nginx

---

apiVersion: v1
kind: Endpoints
metadata:
  name: endpoint-service # nome do Endpoint deve ser o mesmo do Service
subsets:
  - addresses:
      - ip: 10.244.0.10 # ip externo (dns public)
      - ip: 10.244.0.9  # ip do pod apache
      - ip: 10.244.0.10 # ip do pod nginx
    ports:
      - port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: endpoint-service # nome do Service deve ser o mesmo do Service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
