apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  completions: 5
  completionMode: "Indexed"
  parallelism: 5
  activeDeadlineSeconds: 10
  backoffLimit: 2
  template:
    metadata:
      name: my-job-pod
    spec:
      containers:
      - name: job-container-busybox
        image: busybox
        command:
        - "bin/sh"
        - "-c"
        - "for i in 1 2; do echo [random number][$(( 1 + RANDOM + 100))];done"
      restartPolicy: Never