apiVersion: v1
kind: Pod
metadata:
  name: my-pod-secret
spec:
  containers:
  - name: my-container
    image: nginx
    envFrom:
    - secretRef:
        name: my-secret
        optional: false

---

apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  user: YWRtaW4K
  password: YWRtaW4tYWRtaW4K
stringData:
  database-name: mariadb
immutable: false