# Versão da API do Kubernetes e tipo de recurso (Service)
apiVersion: v1

# Tipo de recurso (Service)
kind: Service

# Metadados para o serviço, incluindo o nome
metadata:
  name: flask-service

# Especificações para o serviço
spec:
  # Seletor para determinar quais pods serão incluídos no serviço
  selector:
    app: flask-app # !!!! aqui ocorre o link entre o Service criado aqui com o Deployment

  # Definição das portas para o serviço
  ports:
    - protocol: 'TCP'     # Protocolo utilizado (TCP)
      port: 5000           # Porta exposta no serviço
      targetPort: 5000     # Porta do pod de destino

  # Tipo de serviço, neste caso, LoadBalancer
  type: LoadBalancer
