# Definindo a versão da API do Kubernetes e o tipo de recurso como Deployment
apiVersion: apps/v1
kind: Deployment

# Metadados para o Deployment, incluindo o nome do deployment
metadata:
  name: flask-app-deployment

# Especificações para o Deployment, como o número de réplicas e o seletor
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-app

  # Template para os pods gerados pelo Deployment
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      # Especificações do pod, incluindo os containers que serão executados
      containers:
        - name: flask
          image: pedrojjesus/flask-kubernetes-project:2
