apiVersion: v1
kind: Pod
metadata:
  name: service-pod
  labels:
    apps: service-app

spec:
  containers:
    - name: tomcat-container
      image: tomcat
    - name: redis-container
      image: redis