apiVersion: v1
kind : Service
metadata:
  name: service-statefulset
spec:
  ports:
  - port: 80
  clusterIP: None
  selector:
    app: nginx-pod

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: nginx-pod
  serviceName: "service-statefulset"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.23.1
        volumeMounts:
        - name: persistent-volume
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: persistent-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 128Mi